[geany]
color_scheme=nodesktop.conf
default_open_path=/home/nodesktop
pref_main_load_session=false
pref_main_save_winpos=false
pref_main_save_wingeom=false
pref_main_confirm_exit=true
pref_editor_new_line=true
pref_editor_default_new_encoding=UTF-8

[VTE]
font=JetBrains Mono 11
colour_fore=#D7DBD2
colour_back=#111612
