# Nodesktop interactive shell configuration
case $- in
  *i*) ;;
  *) return ;;
esac

# Match the Bash-it profile used on the primary workstation.
export BASH_IT=/opt/bash-it
export BASH_IT_THEME=zork
unset MAILCHECK
export IRC_CLIENT=irssi
export TODO=t

if [[ -r "${BASH_IT}/bash_it.sh" ]]; then
  source "${BASH_IT}/bash_it.sh"
else
  PS1='\[\e[38;5;10m\]\u@\h\[\e[0m\]:\[\e[38;5;14m\]\w\[\e[0m\]\\$ '
fi

export PATH="${PATH}:${HOME}/bin"
[[ -r "${HOME}/.local/bin/env" ]] && source "${HOME}/.local/bin/env"
