color_theme = "nodesktop"
theme_background = True
truecolor = True
rounded_corners = False
graph_symbol = "braille"
update_ms = 1000
proc_gradient = True
proc_colors = True
show_disks = True
show_swap = True
